export enum BusinessCategoryType {
  Hairdresser = 'hairdresser',
  Barber = 'barber',
  Nails = 'nails',
  Beauty_parlor = 'beauty_parlor',
  Eyebrows_and_eyelashes = 'eyebrows_and_eyelashes',
  Massage = 'massage',
  Physiotherapy = 'physiotherapy',
  Makeup = 'makeup',
  Bridal_makeup = 'bridal_makeup',
  Dietician = 'dietician',
  Personal_trainer = 'personal_trainer',
  Dentist = 'dentist',
  Podiatry = 'podiatry',
  Aesthetic_medicine = 'aesthetic_medicine',
  Epilation = 'epilation',
  Tattoo_studio = 'tattoo_studio',
  Piercing = 'piercing',
  Health = 'health',
  Natural_medicine = 'natural_medicine',
  Psychotherapy = 'psychotherapy',
  Other = 'other',
}
